INSERT INTO stocks VALUES (1, 500,'TATA');
INSERT INTO stocks VALUES (2, 1000,'TCS');
INSERT INTO stocks VALUES (3, 90,'ZOMATO');
INSERT INTO stocks VALUES (4, 1500,'PAYTM');
INSERT INTO stocks VALUES (5, 1000,'IRCTC');
INSERT INTO stocks VALUES (6, 900,'HAPPIEST MINDS');
